### ISSUE TITLE
Specifying data types for attributes in .cvs files

### ISSUE THREAD

**Issue by visenger** [dbunibas/BART#3]
Hello,

how would you specify a data type for an attribute while importing a .cvs file
Currently every attribute from the .cvs file is parsed as text (data type).
How can I configure that a particular attribute has a specific data type?

For example:

`zip, city, households, pensioner`

`00AA,City of London,4338,626`

`00AB,Barking and Dagenham,67273,10226`

`00AB,Barking and Dagenham,67274,10225`

`00AC,Barnet,126944,17180`

Two attributes: households and pensioners,  are parsed as text, but should be an integer.

Thank you in advance.

**Comment by donatellosantoro** [comment]
Hi @visenger, thanks for your question. 
In order to configure the type of an attribute in the csv file you need to modify the header adding the type in brackets. The supported types are "integer", "real", "boolean" and "date". In your example
`zip, city, households (integer), pensioner (real)`

See fe9befb

**Comment by visenger** [comment]
Thank you, @donatellosantoro ! Works pretty well, and now I can use outlier generation :+1:
